Handling Imbalanced Dataset
1. Up Sampling
2. Down Sampling

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Set the random seed for reproducibility
np.random.seed(123)

#Creating a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [3]:
n_class_0,n_class_1

(900, 100)

In [4]:
## Create my dataframe with imbalanced Dataset
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [5]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [6]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [7]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [8]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [9]:
## upsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [13]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\venka\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.26.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.0 kB ? eta -:--:--
     ------------------- ------------------ 30.7/61.0 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 465.2 kB/s eta 0:00:00
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/8.0 MB 1.7 MB/s eta 0:00:05
   - -------------------------------------- 0.2/8.0 MB 2.5 MB/s eta 0:00:04
   -- ------------------------------------- 0.5/8.0 MB 4.8 MB/s eta 0:00:02
   ---- ----------------------------------- 0.9/8.0 MB 5.4 MB/s eta 0:00:02
   ------ --------------------------------- 1.2/8.0 MB 6.0 MB/s eta 0:00:02
   ------ --------------------------------- 1.3/8.0 MB 5.1 MB/s eta 0:00:02
   -------- ------------------------------- 1.8/8.0 MB 5.7 MB/s eta 0:00:02
   --------- ------------------------------ 1.9/8.0 MB 5.5 MB/s eta 0:00:02
   ---------- ----------------------------- 2.0/8.0 MB 5.1 MB/s eta 0:00:02
   ---------- ----------------------------- 2.2/8.0 MB 4.9 MB/s eta 0:00:02
   ----------- ---------------------------- 2.3/8.0 MB 4.6 MB/s eta 0:00:02
   ------------ --------------------------- 2.4/8.0 MB 4.7 MB/s eta 0:00:02
   ------------ --------------------------- 2.5/8.0 MB 4.5 MB/s eta 0:00:02
   ------------- -------------------------- 2.7/8.0 MB 4.2 MB/s eta 0:00:02
   -------------- ------------------------- 2.9/8.0 MB 4.1 MB/s eta 0:00:02
   --------------- ------------------------ 3.0/8.0 MB 4.2 MB/s eta 0:00:02
   --------------- ------------------------ 3.1/8.0 MB 4.1 MB/s eta 0:00:02
   ---------------- ----------------------- 3.3/8.0 MB 4.0 MB/s eta 0:00:02
   ----------------- ---------------------- 3.4/8.0 MB 4.0 MB/s eta 0:00:02
   ----------------- ---------------------- 3.6/8.0 MB 3.9 MB/s eta 0:00:02
   ------------------ --------------------- 3.6/8.0 MB 3.8 MB/s eta 0:00:02
   ------------------ --------------------- 3.7/8.0 MB 3.7 MB/s eta 0:00:02
   ------------------- -------------------- 3.9/8.0 MB 3.7 MB/s eta 0:00:02
   ------------------- -------------------- 3.9/8.0 MB 3.6 MB/s eta 0:00:02
   ------------------- -------------------- 3.9/8.0 MB 3.6 MB/s eta 0:00:02
   -------------------- ------------------- 4.0/8.0 MB 3.5 MB/s eta 0:00:02
   -------------------- ------------------- 4.2/8.0 MB 3.4 MB/s eta 0:00:02
   --------------------- ------------------ 4.3/8.0 MB 3.4 MB/s eta 0:00:02
   ---------------------- ----------------- 4.5/8.0 MB 3.4 MB/s eta 0:00:02
   ----------------------- ---------------- 4.6/8.0 MB 3.4 MB/s eta 0:00:01
   ----------------------- ---------------- 4.7/8.0 MB 3.4 MB/s eta 0:00:01
   ----------------------- ---------------- 4.8/8.0 MB 3.4 MB/s eta 0:00:01
   ------------------------ --------------- 4.9/8.0 MB 3.3 MB/s eta 0:00:01
   ------------------------ --------------- 5.0/8.0 MB 3.3 MB/s eta 0:00:01
   ------------------------- -------------- 5.1/8.0 MB 3.1 MB/s eta 0:00:01
   ------------------------- -------------- 5.2/8.0 MB 3.1 MB/s eta 0:00:01
   -------------------------- ------------- 5.2/8.0 MB 3.1 MB/s eta 0:00:01
   -------------------------- ------------- 5.3/8.0 MB 3.1 MB/s eta 0:00:01
   -------------------------- ------------- 5.4/8.0 MB 3.0 MB/s eta 0:00:01
   --------------------------- ------------ 5.5/8.0 MB 3.0 MB/s eta 0:00:01
   --------------------------- ------------ 5.6/8.0 MB 3.0 MB/s eta 0:00:01
   ---------------------------- ----------- 5.6/8.0 MB 2.9 MB/s eta 0:00:01
   ---------------------------- ----------- 5.7/8.0 MB 2.9 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.0 MB 2.9 MB/s eta 0:00:01
   ---------------------------- ----------- 5.8/8.0 MB 2.8 MB/s eta 0:00:01
   ----------------------------- ---------- 5.9/8.0 MB 2.8 MB/s eta 0:00:01
   ----------------------------- ---------- 5.9/8.0 MB 2.7 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.0 MB 2.7 MB/s eta 0:00:01
   ------------------------------ --------- 6.1/8.0 MB 2.7 MB/s eta 0:00:01
   ------------------------------ --------- 6.1/8.0 MB 2.7 MB/s eta 0:00:01
   ------------------------------- -------- 6.2/8.0 MB 2.6 MB/s eta 0:00:01
   ------------------------------- -------- 6.3/8.0 MB 2.6 MB/s eta 0:00:01
   ------------------------------- -------- 6.3/8.0 MB 2.6 MB/s eta 0:00:01
   -------------------------------- ------- 6.4/8.0 MB 2.6 MB/s eta 0:00:01
   -------------------------------- ------- 6.5/8.0 MB 2.6 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.0 MB 2.6 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.0 MB 2.6 MB/s eta 0:00:01
   --------------------------------- ------ 6.7/8.0 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 6.7/8.0 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.0 MB 2.5 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.0 MB 2.5 MB/s eta 0:00:01
   ---------------------------------- ----- 6.8/8.0 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 6.9/8.0 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 6.9/8.0 MB 2.3 MB/s eta 0:00:01
   ---------------------------------- ----- 6.9/8.0 MB 2.3 MB/s eta 0:00:01
   ---------------------------------- ----- 7.0/8.0 MB 2.3 MB/s eta 0:00:01
   ---------------------------------- ----- 7.0/8.0 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.0 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 7.1/8.0 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 7.2/8.0 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.0 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.0 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 7.4/8.0 MB 2.2 MB/s eta 0:00:01
   ------------------------------------- -- 7.5/8.0 MB 2.2 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.0 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 7.6/8.0 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 7.7/8.0 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 7.8/8.0 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 7.8/8.0 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  7.9/8.0 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  8.0/8.0 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------  8.0/8.0 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 2.1 MB/s eta 0:00:00
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/36.5 MB 1.7 MB/s eta 0:00:23
   ---------------------------------------- 0.1/36.5 MB 2.1 MB/s eta 0:00:17
   ---------------------------------------- 0.2/36.5 MB 2.0 MB/s eta 0:00:19
   ---------------------------------------- 0.3/36.5 MB 1.9 MB/s eta 0:00:20
   ---------------------------------------- 0.3/36.5 MB 1.8 MB/s eta 0:00:21
   ---------------------------------------- 0.4/36.5 MB 1.6 MB/s eta 0:00:24
    --------------------------------------- 0.5/36.5 MB 1.6 MB/s eta 0:00:24
    --------------------------------------- 0.6/36.5 MB 1.6 MB/s eta 0:00:23
    --------------------------------------- 0.6/36.5 MB 1.6 MB/s eta 0:00:23
    --------------------------------------- 0.7/36.5 MB 1.6 MB/s eta 0:00:23
    --------------------------------------- 0.8/36.5 MB 1.6 MB/s eta 0:00:23
    --------------------------------------- 0.8/36.5 MB 1.6 MB/s eta 0:00:23
    --------------------------------------- 0.9/36.5 MB 1.6 MB/s eta 0:00:23
    --------------------------------------- 0.9/36.5 MB 1.6 MB/s eta 0:00:23
   - -------------------------------------- 1.0/36.5 MB 1.4 MB/s eta 0:00:25
   - -------------------------------------- 1.0/36.5 MB 1.4 MB/s eta 0:00:26
   - -------------------------------------- 1.1/36.5 MB 1.4 MB/s eta 0:00:26
   - -------------------------------------- 1.2/36.5 MB 1.5 MB/s eta 0:00:25
   - -------------------------------------- 1.2/36.5 MB 1.5 MB/s eta 0:00:25
   - -------------------------------------- 1.3/36.5 MB 1.4 MB/s eta 0:00:25
   - -------------------------------------- 1.4/36.5 MB 1.5 MB/s eta 0:00:25
   - -------------------------------------- 1.4/36.5 MB 1.4 MB/s eta 0:00:25
   - -------------------------------------- 1.4/36.5 MB 1.4 MB/s eta 0:00:25
   - -------------------------------------- 1.5/36.5 MB 1.4 MB/s eta 0:00:26
   - -------------------------------------- 1.5/36.5 MB 1.4 MB/s eta 0:00:26
   - -------------------------------------- 1.6/36.5 MB 1.3 MB/s eta 0:00:27
   - -------------------------------------- 1.6/36.5 MB 1.3 MB/s eta 0:00:27
   - -------------------------------------- 1.7/36.5 MB 1.3 MB/s eta 0:00:28
   - -------------------------------------- 1.7/36.5 MB 1.3 MB/s eta 0:00:28
   - -------------------------------------- 1.8/36.5 MB 1.3 MB/s eta 0:00:27
   - -------------------------------------- 1.8/36.5 MB 1.3 MB/s eta 0:00:28
   -- ------------------------------------- 1.9/36.5 MB 1.3 MB/s eta 0:00:28
   -- ------------------------------------- 1.9/36.5 MB 1.3 MB/s eta 0:00:28
   -- ------------------------------------- 2.0/36.5 MB 1.3 MB/s eta 0:00:27
   -- ------------------------------------- 2.1/36.5 MB 1.3 MB/s eta 0:00:27
   -- ------------------------------------- 2.1/36.5 MB 1.3 MB/s eta 0:00:27
   -- ------------------------------------- 2.2/36.5 MB 1.3 MB/s eta 0:00:27
   -- ------------------------------------- 2.2/36.5 MB 1.3 MB/s eta 0:00:27
   -- ------------------------------------- 2.3/36.5 MB 1.3 MB/s eta 0:00:28
   -- ------------------------------------- 2.3/36.5 MB 1.3 MB/s eta 0:00:28
   -- ------------------------------------- 2.4/36.5 MB 1.3 MB/s eta 0:00:28
   -- ------------------------------------- 2.4/36.5 MB 1.2 MB/s eta 0:00:28
   -- ------------------------------------- 2.4/36.5 MB 1.2 MB/s eta 0:00:28
   -- ------------------------------------- 2.4/36.5 MB 1.2 MB/s eta 0:00:28
   -- ------------------------------------- 2.4/36.5 MB 1.2 MB/s eta 0:00:29
   -- ------------------------------------- 2.5/36.5 MB 1.2 MB/s eta 0:00:29
   -- ------------------------------------- 2.5/36.5 MB 1.2 MB/s eta 0:00:29
   -- ------------------------------------- 2.6/36.5 MB 1.2 MB/s eta 0:00:29
   -- ------------------------------------- 2.7/36.5 MB 1.2 MB/s eta 0:00:29
   --- ------------------------------------ 2.7/36.5 MB 1.2 MB/s eta 0:00:29
   --- ------------------------------------ 2.8/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 2.9/36.5 MB 1.2 MB/s eta 0:00:29
   --- ------------------------------------ 2.9/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 3.0/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 3.1/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 3.1/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 3.2/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 3.2/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 3.3/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 3.3/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 3.3/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 3.4/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 3.4/36.5 MB 1.2 MB/s eta 0:00:29
   --- ------------------------------------ 3.5/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 3.5/36.5 MB 1.2 MB/s eta 0:00:28
   --- ------------------------------------ 3.6/36.5 MB 1.2 MB/s eta 0:00:29
   --- ------------------------------------ 3.6/36.5 MB 1.2 MB/s eta 0:00:29
   --- ------------------------------------ 3.6/36.5 MB 1.2 MB/s eta 0:00:29
   ---- ----------------------------------- 3.7/36.5 MB 1.2 MB/s eta 0:00:29
   ---- ----------------------------------- 3.7/36.5 MB 1.2 MB/s eta 0:00:29
   ---- ----------------------------------- 3.8/36.5 MB 1.2 MB/s eta 0:00:29
   ---- ----------------------------------- 3.8/36.5 MB 1.2 MB/s eta 0:00:29
   ---- ----------------------------------- 3.9/36.5 MB 1.2 MB/s eta 0:00:29
   ---- ----------------------------------- 3.9/36.5 MB 1.2 MB/s eta 0:00:29
   ---- ----------------------------------- 4.0/36.5 MB 1.2 MB/s eta 0:00:29
   ---- ----------------------------------- 4.0/36.5 MB 1.2 MB/s eta 0:00:29
   ---- ----------------------------------- 4.1/36.5 MB 1.2 MB/s eta 0:00:28
   ---- ----------------------------------- 4.2/36.5 MB 1.2 MB/s eta 0:00:28
   ---- ----------------------------------- 4.2/36.5 MB 1.2 MB/s eta 0:00:28
   ---- ----------------------------------- 4.3/36.5 MB 1.2 MB/s eta 0:00:28
   ---- ----------------------------------- 4.3/36.5 MB 1.2 MB/s eta 0:00:28
   ---- ----------------------------------- 4.4/36.5 MB 1.2 MB/s eta 0:00:28
   ---- ----------------------------------- 4.5/36.5 MB 1.2 MB/s eta 0:00:28
   ---- ----------------------------------- 4.5/36.5 MB 1.2 MB/s eta 0:00:28
   ---- ----------------------------------- 4.5/36.5 MB 1.2 MB/s eta 0:00:28
   ----- ---------------------------------- 4.6/36.5 MB 1.2 MB/s eta 0:00:28
   ----- ---------------------------------- 4.7/36.5 MB 1.2 MB/s eta 0:00:28
   ----- ---------------------------------- 4.7/36.5 MB 1.2 MB/s eta 0:00:28
   ----- ---------------------------------- 4.8/36.5 MB 1.2 MB/s eta 0:00:28
   ----- ---------------------------------- 4.9/36.5 MB 1.2 MB/s eta 0:00:27
   ----- ---------------------------------- 5.0/36.5 MB 1.2 MB/s eta 0:00:27
   ----- ---------------------------------- 5.0/36.5 MB 1.2 MB/s eta 0:00:27
   ----- ---------------------------------- 5.1/36.5 MB 1.2 MB/s eta 0:00:27
   ----- ---------------------------------- 5.2/36.5 MB 1.2 MB/s eta 0:00:27
   ----- ---------------------------------- 5.3/36.5 MB 1.2 MB/s eta 0:00:26
   ----- ---------------------------------- 5.4/36.5 MB 1.2 MB/s eta 0:00:26
   ----- ---------------------------------- 5.4/36.5 MB 1.2 MB/s eta 0:00:26
   ------ --------------------------------- 5.5/36.5 MB 1.2 MB/s eta 0:00:26
   ------ --------------------------------- 5.6/36.5 MB 1.2 MB/s eta 0:00:26
   ------ --------------------------------- 5.7/36.5 MB 1.2 MB/s eta 0:00:25
   ------ --------------------------------- 5.8/36.5 MB 1.2 MB/s eta 0:00:25
   ------ --------------------------------- 5.9/36.5 MB 1.3 MB/s eta 0:00:25
   ------ --------------------------------- 6.0/36.5 MB 1.3 MB/s eta 0:00:25
   ------ --------------------------------- 6.1/36.5 MB 1.3 MB/s eta 0:00:25
   ------ --------------------------------- 6.2/36.5 MB 1.3 MB/s eta 0:00:24
   ------ --------------------------------- 6.2/36.5 MB 1.3 MB/s eta 0:00:24
   ------ --------------------------------- 6.3/36.5 MB 1.3 MB/s eta 0:00:24
   ------ --------------------------------- 6.3/36.5 MB 1.3 MB/s eta 0:00:24
   ------- -------------------------------- 6.4/36.5 MB 1.3 MB/s eta 0:00:24
   ------- -------------------------------- 6.5/36.5 MB 1.3 MB/s eta 0:00:24
   ------- -------------------------------- 6.5/36.5 MB 1.3 MB/s eta 0:00:24
   ------- -------------------------------- 6.6/36.5 MB 1.3 MB/s eta 0:00:24
   ------- -------------------------------- 6.7/36.5 MB 1.3 MB/s eta 0:00:24
   ------- -------------------------------- 6.8/36.5 MB 1.3 MB/s eta 0:00:23
   ------- -------------------------------- 6.9/36.5 MB 1.3 MB/s eta 0:00:23
   ------- -------------------------------- 7.0/36.5 MB 1.3 MB/s eta 0:00:23
   ------- -------------------------------- 7.1/36.5 MB 1.3 MB/s eta 0:00:23
   ------- -------------------------------- 7.2/36.5 MB 1.3 MB/s eta 0:00:23
   ------- -------------------------------- 7.3/36.5 MB 1.3 MB/s eta 0:00:23
   -------- ------------------------------- 7.4/36.5 MB 1.3 MB/s eta 0:00:22
   -------- ------------------------------- 7.5/36.5 MB 1.3 MB/s eta 0:00:22
   -------- ------------------------------- 7.6/36.5 MB 1.4 MB/s eta 0:00:22
   -------- ------------------------------- 7.7/36.5 MB 1.4 MB/s eta 0:00:22
   -------- ------------------------------- 7.8/36.5 MB 1.4 MB/s eta 0:00:22
   -------- ------------------------------- 7.9/36.5 MB 1.4 MB/s eta 0:00:21
   -------- ------------------------------- 8.0/36.5 MB 1.4 MB/s eta 0:00:21
   -------- ------------------------------- 8.1/36.5 MB 1.4 MB/s eta 0:00:21
   --------- ------------------------------ 8.2/36.5 MB 1.4 MB/s eta 0:00:21
   --------- ------------------------------ 8.4/36.5 MB 1.4 MB/s eta 0:00:21
   --------- ------------------------------ 8.5/36.5 MB 1.4 MB/s eta 0:00:20
   --------- ------------------------------ 8.6/36.5 MB 1.4 MB/s eta 0:00:20
   --------- ------------------------------ 8.6/36.5 MB 1.4 MB/s eta 0:00:20
   --------- ------------------------------ 8.6/36.5 MB 1.4 MB/s eta 0:00:20
   --------- ------------------------------ 8.7/36.5 MB 1.4 MB/s eta 0:00:20
   --------- ------------------------------ 8.8/36.5 MB 1.4 MB/s eta 0:00:20
   --------- ------------------------------ 8.8/36.5 MB 1.4 MB/s eta 0:00:20
   --------- ------------------------------ 8.9/36.5 MB 1.4 MB/s eta 0:00:20
   --------- ------------------------------ 9.0/36.5 MB 1.4 MB/s eta 0:00:20
   ---------- ----------------------------- 9.2/36.5 MB 1.4 MB/s eta 0:00:20
   ---------- ----------------------------- 9.3/36.5 MB 1.4 MB/s eta 0:00:19
   ---------- ----------------------------- 9.4/36.5 MB 1.4 MB/s eta 0:00:19
   ---------- ----------------------------- 9.5/36.5 MB 1.4 MB/s eta 0:00:19
   ---------- ----------------------------- 9.5/36.5 MB 1.4 MB/s eta 0:00:19
   ---------- ----------------------------- 9.6/36.5 MB 1.4 MB/s eta 0:00:19
   ---------- ----------------------------- 9.7/36.5 MB 1.5 MB/s eta 0:00:19
   ---------- ----------------------------- 9.8/36.5 MB 1.5 MB/s eta 0:00:19
   ---------- ----------------------------- 9.8/36.5 MB 1.5 MB/s eta 0:00:19
   ---------- ----------------------------- 9.9/36.5 MB 1.5 MB/s eta 0:00:19
   ---------- ----------------------------- 10.0/36.5 MB 1.5 MB/s eta 0:00:19
   ----------- ---------------------------- 10.1/36.5 MB 1.5 MB/s eta 0:00:19
   ----------- ---------------------------- 10.1/36.5 MB 1.5 MB/s eta 0:00:19
   ----------- ---------------------------- 10.2/36.5 MB 1.5 MB/s eta 0:00:19
   ----------- ---------------------------- 10.3/36.5 MB 1.5 MB/s eta 0:00:19
   ----------- ---------------------------- 10.3/36.5 MB 1.5 MB/s eta 0:00:19
   ----------- ---------------------------- 10.4/36.5 MB 1.4 MB/s eta 0:00:19
   ----------- ---------------------------- 10.4/36.5 MB 1.4 MB/s eta 0:00:19
   ----------- ---------------------------- 10.5/36.5 MB 1.4 MB/s eta 0:00:19
   ----------- ---------------------------- 10.6/36.5 MB 1.5 MB/s eta 0:00:18
   ----------- ---------------------------- 10.6/36.5 MB 1.4 MB/s eta 0:00:18
   ----------- ---------------------------- 10.7/36.5 MB 1.4 MB/s eta 0:00:18

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True, #Sample With replacement
         n_samples=len(df_majority),
         random_state=42
        )

In [15]:
df_minority_upsampled.shape

(900, 3)

In [16]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [17]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down Sampling

In [18]:
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

# Check the class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [19]:
## downsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [20]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=False, # We need to reduce the datapoints
         n_samples=len(df_minority),
         random_state=42
        )

In [22]:
df_majority_downsampled.shape

(100, 3)

In [23]:
df_downsampled=pd.concat([df_majority_downsampled,df_minority])

In [24]:
df_downsampled.target.value_counts()

target
0    100
1    100
Name: count, dtype: int64