### Label Encoding
label encoding and ordinal encoding are two techniques use to encode categorical data as numerical data (Go through Notes)

In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.DataFrame({
    'color' : ['red','blue','green','green','red','green','blue','green']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [17]:
## Create instance of labelEncoder
le = LabelEncoder()
encoded_data = le.fit_transform(df['color'])  #df[] is series and d[[]] is dataframe

In [14]:
encoded_data

array([2, 0, 1, 1, 2, 1, 0, 1])

In [18]:
#We can do it for any new data point 
le.transform(['red','green'])

array([2, 1])

## Ordinal Encoding
you can manually assign the numbers to preserve the real world scale(Ex: low=0,medium=1,high=2)

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
df = pd.DataFrame({
    'size':['small','large','medium','large','large','medium','small']
})

In [21]:
df.head()

     size
0   small
1   large
2  medium
3   large
4   large

In [24]:
## Create an instance of Ordinal encoder
oe = OrdinalEncoder(categories=[['small','medium','large']]) # numbering is given by this order
ordinal_data = oe.fit_transform(df[['size']])

In [25]:
ordinal_data

array([[0.],
       [2.],
       [1.],
       [2.],
       [2.],
       [1.],
       [0.]])

You can see small has 0, medium has 1 and large has 2